### ISSUE TITLE
Refactor/Clean up

### ISSUE THREAD

**Issue by longfellowone** [longfellowone/est#25]
### Notes ###

- https://github.com/launchbadge/realworld-axum-sqlx/blob/837713af32fce83d544993a3d8f7664cbe3354b8/migrations/2_user.sql#L14

### Todo #### 

- [x] Move RUST_LOG to .env
- [x] Move migrate to main
- [x] Refactor app.run()
- [x] Create folder for each resolver
- [x] Change id to table_id, change join queries to using(id)
- [x] Change SQL to lowercase
- [x] Add // language=PostgreSQL to queries
- [x] Change pg_pool to pool
